package_rename_config:
  android:
    app_name: VirtualAid
    package_name: com.srs.virtualaid
    override_old_package: # (Optional) (String) Use this to delete the old folder structure of MainActivity or to use the existing code with the new package name
    lang: # (Optional) (String) The android development language {kotlin(default) or java}

  ios:
    app_name: VirtualAid
    bundle_name: VirtualAid
    package_name: com.srs.virtualaid

  linux:
    app_name: VirtualAid
    package_name: com.srs.virtualaid
    exe_name: virtualaid

  macos:
    app_name: VirtualAid
    package_name: com.srs.virtualaid
    copyright_notice: © 2023 SRS

  web:
    app_name: VirtualAid
    short_app_name: VirtualAid
    description: A virtual assistant application for healthcare

  windows:
    app_name: VirtualAid
    organization: SRS
    copyright_notice: © 2023 SRS
    exe_name: virtualaid
